; SHADREMHOT - USER DEFINED COMMAND PROCEDURE FOR CHECKING WETHER
;              APPLICATION IS ALLOWED TO REMAIN HOT AFTER DISCOVERING
;              THAT ALSO THE SHADOWING PARTNER IS HOT
;
; INPUT PARAMETER:
;                   %APL        (INTEGER 1 .. MAX_APPLICATION_NUMBER,
;                                APPLICATION NUMBER)
; OUTPUT PARAMETER: 
;                   %REMAIN_HOT (BOOLEAN, TRUE OR FALSE)
;
;-END-ABB---------------------------------------------------------------------
