; SHADGOHOT - USER DEFINED COMMAND PROCEDURE FOR CHECKING WETHER
;             APPLICATION IS ALLOWED TO HOT OR NOT WHEN THE SHADOWING
;             HAS DISCOVERED A CONNECTION LOST
;
; INPUT PARAMETER:
;                   %APL        (INTEGER 1 .. MAX_APPLICATION_NUMBER,
;                                APPLICATION NUMBER)
; OUTPUT PARAMETER: 
;                   %GO_HOT     (BOOLEAN, TRUE OR FALSE)
;
;-END-ABB---------------------------------------------------------------------
