;CM =Interface for Monitor Pro Reports, Return all existing report object names
; Function:    SAGR_REPORTS_GET_ALL_QUICK_REPORT_OBJECTS:C
; Version:     3.0 (build 2.3.2012)
; Parameters:  none
; Return data: all report object names from apl:bsv30
; Description: 
;--------------------------------------------------------------------------------------------------
;Revision History
;Date       Vers.    Author Description
;--------------------------------------------------------------------------------------------------

@OUTPUT = %v_ReportObjectNames


